apiVersion: v1
kind: Service
metadata:
  name: devops-backend-service
  namespace: backend
  labels:
    name: devops-backend-service
spec:
  clusterIP: None
  ports:
    - name: devops-backendport
      port: 5000
      targetPort: 5000
  selector:
    app: devops-backend
