apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
  labels:
    name: frontend-service
spec:
  type: LoadBalancer
  ports:
    - name: frontendport
      port: 80
      targetPort: 80
  selector:
    app: frontend
