apiVersion: v1
kind: Service
metadata:
  name: devops-frontend-service
  labels:
    name: devops-frontend-service
spec:
  clusterIP: None
  ports:
    - name: devops-frontendport
      port: 80
      targetPort: 80
  selector:
    app: devops-frontend
