apiVersion: v1
kind: Service
metadata:
  name: devops-nginx-service
  namespace: nginxns
  labels:
    name: devops-nginx-service
spec:
  type: LoadBalancer
  ports:
    - name: devops-nginxport
      port: 443
      targetPort: 443
  selector:
    app: devops-nginx
