apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: docker.io/rohaanoa/backend:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: dockerhub-credential
      
