apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
  labels:
    name: backend-service
spec:
  type: LoadBalancer
  ports:
    - name: backendport
      port: 3000
      targetPort: 3000
  selector:
    app: backend
