apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "devops-admin" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: devops-admin-cluster-binding
subjects:
- name: devops-admin # Name is case sensitive
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-devops-admin
  apiGroup: ""
